# Generated by Django 6.0.5 on 2026-05-16 21:04

import django.contrib.postgres.search
import django.db.models.deletion
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("is_private", models.BooleanField(db_index=True, default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "images_collection",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("source_url", models.URLField(blank=True, max_length=2000)),
                ("image", models.ImageField(blank=True, upload_to="images/originals/")),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="images/thumbnails/"),
                ),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("moderated", "Removed by moderation"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("followers", "Followers only"),
                            ("private", "Private"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "view_count",
                    models.PositiveBigIntegerField(db_index=True, default=0),
                ),
                (
                    "like_count",
                    models.PositiveBigIntegerField(db_index=True, default=0),
                ),
                ("save_count", models.PositiveIntegerField(default=0)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="images.collection",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "db_table": "images_image",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.image",
            ),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="images.image",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "images_like",
            },
        ),
        migrations.CreateModel(
            name="Save",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="images.image",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "images_save",
            },
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["owner", "status"], name="images_imag_owner_i_7f8b03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["status", "privacy", "-created_at"],
                name="images_imag_status_6c71dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["-like_count"], name="images_imag_like_co_bef6bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["-view_count"], name="images_imag_view_co_a43126_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together={("owner", "name")},
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["image", "-created_at"], name="images_like_image_i_6e20c2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "image")},
        ),
        migrations.AlterUniqueTogether(
            name="save",
            unique_together={("user", "image")},
        ),
    ]
