# Generated by Django 6.0.5 on 2026-05-16 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("liked", "liked"),
                            ("saved", "saved"),
                            ("followed", "followed"),
                            ("bookmarked", "bookmarked"),
                            ("commented", "commented"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(blank=True, db_index=True, max_length=36),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "activity_activity",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="activity_ac_actor_i_200108_idx",
                    )
                ],
            },
        ),
    ]
